'use strict';
const fullName = 'Malcolm Abbott';
const isCool = true;
const totalPets = 1;
console.log(`fullName: ${fullName}`);
console.log(`isCool: ${isCool}`);
console.log(`totalPets: ${totalPets}`);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
const unknown = null;
console.log(`unknown: ${unknown}`);
console.log('typeof unknown:', typeof unknown);
let never;
console.log(`never: ${never}`);
console.log('typeof never:', typeof never);
